# This is a basic workflow that is manually triggered

name: manual-build-hbase

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      name:
        # Friendly description to be shown in the UI instead of 'version'
        description: 'version'
        # Default value if no value is explicitly provided
        default: 'v1'
        # Input has to be provided for the workflow to run
        required: true
  push:
    branches: [ bess-Action/2.4.14 ]

jobs:
  build:
    runs-on: ubuntu-20.04
    #https://github.com/actions/runner-images
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: rel/2.4.14
      - name: build hbase-2.4.14
        env:
          JAVA_HOME: /usr/lib/jvm/java-8-openjdk-amd64
        run: |
          sudo lsb_release -a
          sudo uname -m
          sudo apt-get -y install openjdk-8-jdk
          sudo apt-get -y install maven
          mkdir staging
          mvn clean package -DskipTests assembly:single -Dhadoop.profile=3.0 -Dhadoop-three.version=3.3.1
          mkdir staging && cp /home/runner/work/hbase/hbase/hbase-assembly/target/*.tar.gz staging
      - name: upload-artifact
        uses: actions/upload-artifact@v3
        with:
          name: package
          path: staging
